apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quant-data
  namespace: quant-trading
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
